### ISSUE TITLE
right click: Hide, Collapse, Expand

### ISSUE THREAD

**Issue by Samiwaa** [nikolimaj/graph_app#25]
hide: hide current node (might need another general button or something to make hidden visible again...)
expand: show all related nodes to the current one (may need the filter or something...)
collapse: remove expanded nodes

**Comment by nikolimaj** [comment]
https://reactflow.dev/docs/api/nodes/node-toolbar/

**Comment by Samiwaa** [comment]
Collapse: several possibilities
Greedy: just collapse/remove all children and their children (recursive)
or
Only remove children when there are no other edges (but then we have the problem that a child with children itself doesn't collapse)
so a child should further save which node it got expanded from (possibly a list) and keep it if there are other nodes it got expanded from, because it might have a "neighbor edge" to another node that it hasn't been expended from

**Comment by chri-gassner** [comment]
Backend: Expand
Frontend Collaps/hide
