### ISSUE TITLE
Check data, past das ????

### ISSUE THREAD

**Issue by chri-gassner** [nikolimaj/graph_app#30]
## Short description

Please provide a short description which summarizes the idea behind this feature request and why this is useful.

## User stories

* As a *user*, I want to ... so that ...

Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues 😃

**Comment by LenaOppitz** [comment]
Tested various Traits form EFO, CHEBI, MONDO, HP, GO, NCIT, Orphanet
Errors: Testing IDs beginning with API Name (no number following) fails=> not important, we not have a open search -> we have a details button
When no internet connection, when Button Details is clicked -> fail
