### ISSUE TITLE
Fix autocomplete

### ISSUE THREAD

**Issue by Samiwaa** [nikolimaj/graph_app#40]
When entering a gene name in the search bar, the full gene name gets suggested. This is technically not wrong but it won't work for retrieving the gene since the id is needed.
So either only return the matching id (even when the search term is part of a gene name) or maybe return dictionary or something containing id and name, then displaying the name but using the id when clicking on it...

**Comment by chri-gassner** [comment]
AutoComplete now Returns a List of List [["id", "symbol"],..] and Frontend handles to separate Data into id-List und symbol-list. Id-list used for Backend, SymbolList for Multisearch
